include: package:flame_lint/analysis_options.yaml
analyzer:
  errors:
    avoid_dynamic_calls: ignore
    lines_longer_than_80_chars: ignore
    require_trailing_commas: ignore
    use_setters_to_change_properties: ignore
