name: flame_game
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  amplitude_flutter: ^3.13.0
  a_star_algorithm: ^0.3.1
  flame: ^1.18.0
  flame_tiled: ^1.20.2
  flame_tiled_utils: ^1.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  flutter_speed_dial: ^7.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  vector_math: ^2.1.4

dev_dependencies:
  flame_lint: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/images/
    - assets/json/
    - assets/json/quests/