name: flame_game
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  a_star_algorithm: ^0.3.1
  flame: ^1.10.0
  flame_tiled: ^1.15.0
  flame_tiled_utils: ^1.1.1
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flame_lint: ^1.0.0

flutter:
  assets:
    - assets/tiles/
    - assets/images/
    - assets/json/
