<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.1" name="4 Walls, Floor &amp; Doors" tilewidth="16" tileheight="16" tilecount="40" columns="8">
 <image source="../images/4 Walls, Floor &amp; Doors.png" width="128" height="80"/>
 <tile id="0" type="blocked"/>
 <tile id="1" type="blocked"/>
 <tile id="2" type="blocked"/>
 <tile id="3" type="blocked"/>
 <tile id="4" type="blocked"/>
 <tile id="5" type="blocked"/>
 <tile id="6" type="blocked"/>
 <tile id="7" type="blocked"/>
 <tile id="8" type="blocked"/>
 <tile id="10" type="blocked"/>
 <tile id="11" type="blocked"/>
 <tile id="12" type="blocked"/>
 <tile id="13" type="blocked"/>
 <tile id="14" type="blocked"/>
 <tile id="15" type="blocked"/>
 <tile id="16" type="blocked"/>
 <tile id="17" type="blocked"/>
 <tile id="18" type="blocked"/>
 <tile id="19" type="blocked"/>
 <tile id="20" type="blocked"/>
 <tile id="21" type="blocked"/>
 <tile id="22" type="blocked"/>
 <tile id="23" type="blocked"/>
 <tile id="24" type="blocked"/>
 <tile id="25" type="blocked"/>
 <tile id="26" type="blocked"/>
 <tile id="27" type="blocked"/>
 <tile id="28" type="blocked"/>
 <tile id="29" type="blocked"/>
 <tile id="30" type="blocked"/>
 <tile id="31" type="blocked"/>
 <tile id="32" type="blocked"/>
 <tile id="33" type="blocked"/>
 <tile id="34" type="blocked"/>
 <tile id="35" type="blocked"/>
 <tile id="36" type="blocked"/>
 <tile id="37" type="blocked"/>
 <tile id="38" type="blocked"/>
 <tile id="39" type="blocked"/>
</tileset>
